### ISSUE TITLE
Error: Cannot find module 'pbkdf2'

### ISSUE THREAD

**Issue by bkmeneguello** [chriscohoat/rai-wallet#1]
After `npm init` and `npm i --save rai-wallet` and
```js
var RaiWallet = require('rai-wallet');
var Wallet = RaiWallet.Wallet;
console.log(Wallet);
```

**Comment by chriscohoat** [comment]
Hi @bkmeneguello I just started a new React app from scratch and it worked fine. What type of site are you building so I can troubleshoot? Or are you using node.js?

**Comment by bkmeneguello** [comment]
I'm using node 9.3.0 and npm 5.6.0.
I created an empty project following the steps above. It worked after `npm i --save pbkdf2`.

**Comment by chriscohoat** [comment]
I'll add pbkdf2 as a dependency to this repo so that it pulls it in correctly...thanks for the heads up! (I haven't had time to test with node, only with React and React Native)

**Comment by bkmeneguello** [comment]
It's working perfectly. Thanks!
