### ISSUE TITLE
Is there a documentation or description as to how rai-wallet can be used local / offline?

### ISSUE THREAD

**Issue by SuperHenkie** [chriscohoat/rai-wallet#9]
Looks like a very useful project and would love to use this to setup a local / offline wallet (for cold storage).

However I have no clue where to start. Is there a documentation or description somewhere? Or some guidelines or hints how to get started?

**Comment by chriscohoat** [comment]
Hi @SuperHenkie ... a good wiki article by the Nanocurrency team on how to create a cold wallet is here: https://github.com/nanocurrency/raiblocks/wiki/Creating-a-Cold-Wallet

This repo is more for developing your own Javascript wallet implementation, either in the browser or with React Native.
